### ISSUE TITLE
bug: Using more than 1 GPU causes random stalls and exceptions

### ISSUE THREAD

**Issue by VassilisVassiliadis** [foundation-model-stack/fms-hf-tuning#81]
## Describe the bug

This issue started happening sometime last couple of weeks and the observed behaviour is not deterministic. 

When using 2 GPUs, sometimes both GPUs are at 100% utilization, the script runs and terminates successfully in the expected time (e.g. for an artificial dataset within about 4 minutes). Other times, one GPU is constantly at 100% utilization, the other at 0% and the script never terminates or raises an encounters a Segmentation Fault which kills the python interpreter. A third scenario has both GPUs at 100% utilization and the script never completes or encounters a Segmentation Fault.

## Platform

Please provide details about the environment you are using, including the following:

- Interpreter version: python 3.9
- Library version: https://github.com/foundation-model-stack/fms-hf-tuning/commit/a93e3bca1229ca7239281630fa04b7fd121e1a95
  - Also tested with commit 304b1793ac851ede6ca7c346729adec7098385c3

## Sample Code

```bash
export CUDA_VISIBLE_DEVICES=0,1
model="hf-tiny-model-private/tiny-random-BloomForCausalLM"
python tuning/sft_trainer.py --output_dir tuned --model_name_or_path ${model} --use_flash_attn=false --max_steps 100  \
        --per_device_train_batch_size 1 \
        --evaluation_strategy no --response_template "\n### Response" --dataset_text_field output --tokenizer_name_or_path ${model} \
        --torch_dtype float32 --data_path common_en_news_combined_512-preprocessed.jsonl
```

## Expected behavior

The script terminates successfully with a reasonable execution time.

## Observed behavior

Using more than 1 GPU causes random stalls there are no exceptions printed. 

There's only one warning that I can see:

> /tmp/ray/session_2024-03-06_12-02-23_662564_1/runtime_resources/pip/a1249035b2784b570db2ef4c0bc247b20dd7f217/virtualenv/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.

I've switched on debug logs and I can see the AIMStack observer printing debug logs to the terminal but there are no printouts from HF/Torch about processing steps. The job does not terminate even after running for 17 hours for an experiment which is expected to last about 4 minutes.

Occasionally I see this exception:

> RuntimeError: NCCL Error 3: internal error - please report this issue to the NCCL developers

and when I do then the script terminates.

I also sometimes see segmentation faults, next time I run into one I'll make a note and add it to this issue.

## Additional context

I'm launching the equivalent of the above script but as a ray remote method with a `@ray.remote(num_gpus=2)`. I suspect that  some one or more dependency packages have changed sometime in the last couple of weeks and these changes are causing the problems I'm facing.

**Comment by VassilisVassiliadis** [comment]
Due to https://github.com/foundation-model-stack/fms-hf-tuning/issues/62 I'm using `transformers<4.38.0` in my virtual environment.

**Comment by VassilisVassiliadis** [comment]
I'm putting together a minimum script that demonstrates the above behaviour and then I'll upload it here.

**Comment by VassilisVassiliadis** [comment]
Here's a script you can use that reproduces the above behaviour. I'm finding that the larger the model the bigger the chances that the code either hangs or raises a Segmentation Fault.

```python
"""To run this script:

1. pip install "ray[default]"
2. python3 failure.py $model_name_or_path
   - if you have a remote ray cluster,
     use `ray job submit --working-dir $PWD --no-wait -v --  python3 failure.py $model_name_or_path`
"""

# Standard
import os
import sys

# First Party
import ray


def dataset_construct(
    path: str,
    size: int = 80,
    population: int = 100,
    prompt: str = "Complete the following text:\n\n",
    delimiter: str = "\n\n### Response:",
):
    # This is just something to auto-generate a dataset
    sample = [
        x
        for x in """Contribution shall mean any work of authorship, including the original version of the Work and any 
        modifications or additions to that Work or Derivative Works thereof, that is intentionally submitted to 
        Licensor for inclusion in the Work by the copyright owner or by an individual or Legal Entity authorized 
        to submit on behalf of the copyright owner. For the purposes of this definition, submitted means any form of 
        electronic, verbal, or written communication sent to the Licensor or its representatives, including but not 
        limited to communication on electronic mailing lists, source code control systems, and issue tracking systems 
        that are managed by, or on behalf of, the Licensor for the purpose of discussing and improving the Work, 
        but excluding communication that is conspicuously marked or otherwise designated in writing by the copyright 
        owner as Not a Contribution.""".split()
        if x
    ]

    # Standard
    import json
    import random

    random.seed(42)

    def gen_line():
        return " ".join((random.choice(sample) for _ in range(size)))

    dataset = []
    for _ in range(population):
        entry = {"output": " ".join((prompt, gen_line(), delimiter, gen_line()))}
        dataset.append(json.dumps(entry))

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(dataset))


def wrapper(model_name_or_path: str, use_flash_attn: bool):
    dataset_path = "artificial.jsonl"
    dataset_construct(dataset_path)

    try:
        # Third Party
        from transformers import TrainingArguments
        from transformers.utils import logging
        import pkg_resources

        # Local
        from tuning.config.configs import (
            DataArguments,
            ModelArguments,
            TrainingArguments,
        )
        import tuning.sft_trainer

        installed_packages = pkg_resources.working_set
        installed_packages = sorted(
            ["%s==%s" % (i.key, i.version) for i in installed_packages]
        )

        logging.set_verbosity_debug()

        print(f"Installed packages {installed_packages}")

        data_args = DataArguments(
            data_path=dataset_path,
            response_template="\n\n### Response:",
            dataset_text_field="output",
        )

        model_args = ModelArguments(
            model_name_or_path=model_name_or_path, use_flash_attn=use_flash_attn
        )

        train_args = TrainingArguments(
            save_strategy="no",
            per_device_train_batch_size=1,
            output_dir="outputs",
            max_steps=100,
        )

        tuning.sft_trainer.train(
            model_args=model_args,
            data_args=data_args,
            train_args=train_args,
            peft_config=None,
        )
    finally:
        os.remove(dataset_path)


def run(model_name_or_path: str, num_gpus: int, use_flash_attn: bool = False):
    runtime_env = {
        "env_vars": {
            # So that aim doesn't try to create ~/.aim_profile
            "HOME": "/tmp/",
            "AIM_UI_TELEMETRY_ENABLED": "0",
            "LOGLEVEL": "DEBUG",
        },
        "pip": {
            "packages": [
                "packaging",
                "wheel",
                "numpy",
                "accelerate>=0.20.3",
                # Deals with bug in issue 62
                "transformers>=4.31,<4.38.0",
                "torch",
                "aim>=3.18",
                "sentencepiece",
                "tokenizers>=0.13.3",
                "tqdm",
                "trl",
                "ninja",
                "peft>=0.8.0",
                "datasets>=2.15.0",
                "fire",
                "jwt",
                # This installs the latest commit in the fms-hf-tuning repo
                f"tuning@git+https://github.com/foundation-model-stack/fms-hf-tuning",
            ]
        },
    }

    if use_flash_attn:
        # If you're using flash-attn make sure to compile it and install it first
        runtime_env["pip"]["packages"].append("flash-attn")
    print("Launching task")
    method = ray.remote(
        num_gpus=num_gpus,
        num_cpus=max(1, num_gpus) * 2,
        runtime_env=runtime_env,
        max_retries=0,
    )(wrapper)

    ray.get(
        method.remote(
            model_name_or_path=model_name_or_path, use_flash_attn=use_flash_attn
        )
    )


def main():
    ray.init()
    if len(sys.argv) == 2:
        model_name_or_path = sys.argv[1]
    else:
        # If using a remote ray cluster use
        # ray job submit --working-dir $PWD --no-wait -v --  python3 failure.py $model_name_or_path
        raise ValueError("Use python3 failure.py $model_name_or_path")

    run(model_name_or_path=model_name_or_path, use_flash_attn=False, num_gpus=2)


if __name__ == "__main__":
    main()
```

**Comment by VassilisVassiliadis** [comment]
This all worked fine till about 2 weeks ago

**Comment by Ssukriti** [comment]
could you try on latest main @VassilisVassiliadis and update, as some PRs were merged ? you do not need to cap transformers library . 
If issue still persists we will help investigate. 

also FYI @fabianlim as you may be interested

**Comment by VassilisVassiliadis** [comment]
@Ssukriti through trial and error I reached the set of pinned dependencies that I list in my above script. It now works for pt and lora (details in comment). 

Note that I didn't test full finetuning as my models are too big to train with DDP and FSDP requires multiple processes which is awkward to achieve with `ray`.

**Comment by VassilisVassiliadis** [comment]
I think that the most recent commits to fms-hf-tuning plus the package versions that I installed in my virtual environment resolve the issue.

**Comment by Ssukriti** [comment]
ok lets close it for now and keep an eye on it. If occurs again, please open new one
